### PR TITLE
[Merged by Bors] - release 0.3.0

### PR DESCRIPTION
**Pull request by adwk67**
# Description

Release 0.3.0. No `docs/templating_vars.yaml` file to update.

## Review Checklist

- [x] Code contains useful comments
- [x] CRD change approved (or not applicable)
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by sbernauer — APPROVED** [review]
No changes since 0.2.1  but fine for me :+1:

**Comment by teozkr** [comment]
The CHANGELOG looks suspiciously empty, do we want to add a note about generally updated dependencies and stuff?

**Comment by adwk67** [comment]
> The CHANGELOG looks suspiciously empty, do we want to add a note about generally updated dependencies and stuff?

Good point. Have checked and only changes since 0.2.1 was templating and dependency stuff. Will check for similar with other operators.

**Comment by adwk67** [comment]
bors merge

**Comment by adwk67** [comment]
bors cancel

**Comment by adwk67** [comment]
bors merge

**Pull request closed without merging**
